### PR TITLE
Support Flutter 3.0.0

### PR DESCRIPTION
**Pull request by augusting52**
change kotlin verison from 1.3.72 to 1.5.31

### CODE REVIEW

**Comment by asaarnak** [comment]
https://developer.android.com/studio/releases/gradle-plugin#min-kotlin-version
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':image_gallery_saver' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.72

**Comment by carlosetorresm** [comment]
as a quick fix :
https://github.com/hui-z/image_gallery_saver/issues/220#issuecomment-1291778299
> Add to your `pubspec.yaml`
> 
> ```
> dependency_overrides:
>   image_gallery_saver:
>     git:
>       url: https://github.com/hui-z/image_gallery_saver
>       ref: master
> ```

**Comment by palenik-martin** [comment]
Can we use kotlin version 1.8.10?

**Comment by woodwen** [comment]
update kotlin_version = '1.7.10'

**Pull request closed without merging**
