### PR TITLE
Update

### PR DESCRIPTION
**Pull request by woodwen**
1.Upgrade flutter version to 3.10.5
2.Android build tools are upgraded to 7.3.0
3.Optimize the Android plugin library code

### CODE REVIEW

**Comment by x99mosealaaverga** [comment]
dependencies:
  image_gallery_saver: '^2.0.3'

**Review by Genio40921 — COMMENTED** [review]
G

**Review by Genio40921 — COMMENTED** [review]
Upd

**Review by bank8641 — APPROVED** [review]

**Review by bank8641 — APPROVED** [review]

**Review by bank8641 — APPROVED** [review]

**Review by bank8641 — APPROVED** [review]

**Review by bank8641 — APPROVED** [review]

**Review by bank8641 — APPROVED** [review]

**Pull request merged**
