### PR TITLE
🔥[Urgent] Support AGP 8 and Fix Compile Issue

### PR DESCRIPTION
**Pull request by knottx**
1. Support AGP 8
2. Fix Compile Issue #272 

For people who are waiting for this 
you can use this in your `pubspec.yaml`
```
dependency_overrides:
  image_gallery_saver:
    git:
      url: https://github.com/knottx/image_gallery_saver.git
      ref: knottx
```

### CODE REVIEW

**Comment by krutarth-vaishnav** [comment]
@knottx, Thanks. I'm using your link in my code. make sure you don't remove that.

**Comment by knottx** [comment]
@hyjfine @woodwen  please 🥹

**Comment by mkobuolys** [comment]
Any plans to merge this any time soon?

**Comment by knottx** [comment]
go to #295

**Pull request closed without merging**
