### PR TITLE
jcenter to mavenCentral

### PR DESCRIPTION
**Pull request by vasilich6107**
fix for #228

### CODE REVIEW

**Comment by BetterB0y** [comment]
can we merge this @woodwen ?
currently, the jcenter is down, and it's better if we can fix this on image_gallery_saver.
thank you

**Comment by ipcjs** [comment]
阿。这。。。😰

@woodwen
Can you just click the `Merge`?

**Comment by BetterB0y** [comment]
@tomsun Can you merge this PR for future reliability?

For future reference, jcenter has been deprecated, hence why this change was suggested:

> JFrog, the company that maintains the JCenter artifact repository used by many Android projects, made JCenter a read-only repository on March 31st, 2021. According to [the announcement](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), JCenter will allow downloads of existing artifacts indefinitely.
>
> Developers who publish artifacts on JCenter should migrate their packages to a new host, such as [Maven Central](https://maven.apache.org/repository/index.html).

https://developer.android.com/studio/build/jcenter-migration

**Comment by tomsun** [comment]
@BetterB0y @vasilich6107 not my repo, sorry, I just commented on another PR as an innocent bystander... 🙃

@xqqlv and @woodwen seem to be the ones who have commited to master during the last year. Although access to the account that was used to push to pub.dev might or might not be a separate matter

**Pull request closed without merging**
